### ISSUE TITLE
support scala-js 1.0.0-M1

### ISSUE THREAD

**Issue by xuwei-k** [scala-native/sbt-crossproject#45]
- https://github.com/xuwei-k/scalaz/commit/9941862a313f1cf6263402f627196f179baf9205
- https://travis-ci.org/xuwei-k/scalaz/jobs/249328893

```
[info] Compiling 5 Scala sources to /home/travis/build/xuwei-k/scalaz/project/target/scala-2.10/sbt-0.13/classes...
exception when typing scalajscrossproject.ScalaJSCrossPlugin.autoImport/class scala.reflect.internal.Trees$Select
bad symbolic reference. A signature in ScalaJSCrossPlugin.class refers to term impl
in package org.scalajs.sbtplugin which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling ScalaJSCrossPlugin.class. in file /home/travis/build/xuwei-k/scalaz/project/build.scala
scala.reflect.internal.Types$TypeError: bad symbolic reference. A signature in ScalaJSCrossPlugin.class refers to term impl
in package org.scalajs.sbtplugin which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling ScalaJSCrossPlugin.class.
	at scala.reflect.internal.pickling.UnPickler$Scan.toTypeError(UnPickler.scala:847)
	at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.complete(UnPickler.scala:854)
	at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.load(UnPickler.scala:863)
	at scala.reflect.internal.Symbols$Symbol.typeParams(Symbols.scala:1489)
	at scala.tools.nsc.transform.SpecializeTypes$$anonfun$scala$tools$nsc$transform$SpecializeTypes$$normalizeMember$1.apply(SpecializeTypes.scala:798)
```

/cc @sjrd

**Comment by sjrd** [comment]
You must remove `sbt-scalajs-crossproject` when using Scala.js 1.0.0-M1. Its functionality is now built in `sbt-scalajs`.

**Comment by xuwei-k** [comment]
Oh, I see. thanks!
